create TABLE IVR_liveperson_log (
ID BIGINT IDENTITY(1,1) NOT NULL,
GUID varchar(6000),
URL VARCHAR(2000),
POSTCONTENT VARCHAR(6000),
ARGS VARCHAR(6000),
ERROR VARCHAR(6000),
RESPONSE VARCHAR(6000),
LOGSTAMP DATETIME DEFAULT GETDATE(),
CONSTRAINT pklivepersone_log primary key(
    ID
)
)